#include "server_config.hpp"
#include "platform/fs/file.hpp"
#include <sstream>
#include <algorithm>
#include <cstdlib>

namespace mcserver {

Result<void> ServerConfig::load(const std::string& path) {
    auto content_result = File::read_all_text(path);
    if (!content_result) {
        // File doesn't exist, populate with defaults and save
        set_defaults();
        auto save_result = save(path);
        if (!save_result) {
            return save_result;
        }
        return Result<void>();
    }

    std::istringstream stream(content_result.value());
    std::string line;

    while (std::getline(stream, line)) {
        line = trim(line);

        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') {
            continue;
        }

        // Parse key=value
        auto equals_pos = line.find('=');
        if (equals_pos != std::string::npos) {
            std::string key = trim(line.substr(0, equals_pos));
            std::string value = trim(line.substr(equals_pos + 1));
            properties_[key] = value;
        }
    }

    return Result<void>();
}

Result<void> ServerConfig::save(const std::string& path) const {
    std::ostringstream oss;
    oss << "# Minecraft Beta 1.7.3 Server Properties\n";
    oss << "# Generated by Modern C++ Server\n\n";

    for (const auto& [key, value] : properties_) {
        oss << key << "=" << value << "\n";
    }

    return File::write_all_text(path, oss.str());
}

std::string ServerConfig::get_string(const std::string& key, const std::string& default_value) const {
    auto it = properties_.find(key);
    if (it != properties_.end()) {
        return it->second;
    }
    return default_value;
}

i32 ServerConfig::get_int(const std::string& key, i32 default_value) const {
    auto it = properties_.find(key);
    if (it != properties_.end()) {
        const char* str = it->second.c_str();
        char* end;
        long value = std::strtol(str, &end, 10);
        if (end != str && *end == '\0') {
            return static_cast<i32>(value);
        }
    }
    return default_value;
}

bool ServerConfig::get_bool(const std::string& key, bool default_value) const {
    auto it = properties_.find(key);
    if (it != properties_.end()) {
        std::string value = it->second;
        std::transform(value.begin(), value.end(), value.begin(),
                      [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        return value == "true" || value == "1" || value == "yes";
    }
    return default_value;
}

i64 ServerConfig::get_long(const std::string& key, i64 default_value) const {
    auto it = properties_.find(key);
    if (it != properties_.end()) {
        const char* str = it->second.c_str();
        char* end;
        long long value = std::strtoll(str, &end, 10);
        if (end != str && *end == '\0') {
            return static_cast<i64>(value);
        }
    }
    return default_value;
}

void ServerConfig::set_string(const std::string& key, const std::string& value) {
    properties_[key] = value;
}

void ServerConfig::set_int(const std::string& key, i32 value) {
    properties_[key] = std::to_string(value);
}

void ServerConfig::set_bool(const std::string& key, bool value) {
    properties_[key] = value ? "true" : "false";
}

void ServerConfig::set_long(const std::string& key, i64 value) {
    properties_[key] = std::to_string(value);
}

void ServerConfig::set_defaults() {
    // Network settings
    set_string("server-ip", "");
    set_int("server-port", 25565);

    // World settings
    set_string("level-name", "world");
    set_string("level-seed", "");
    set_int("gamemode", 0);  // 0 = Survival, 1 = Creative
    set_bool("generate-structures", true);

    // Server settings
    set_bool("online-mode", false);  // Offline mode for Beta 1.7.3
    set_int("max-players", 20);
    set_int("view-distance", 10);
    set_string("motd", "A Minecraft Beta 1.7.3 Server");

    // Gameplay settings
    set_bool("spawn-animals", true);
    set_bool("spawn-monsters", true);
    set_bool("spawn-npcs", true);
    set_bool("allow-nether", true);
    set_bool("pvp", true);
    set_bool("allow-flight", false);

    // World generation settings
    set_int("max-build-height", 128);  // Beta 1.7.3 world height
}

std::string ServerConfig::trim(const std::string& str) {
    auto start = std::find_if_not(str.begin(), str.end(), ::isspace);
    auto end = std::find_if_not(str.rbegin(), str.rend(), ::isspace).base();
    return (start < end) ? std::string(start, end) : std::string();
}

} // namespace mcserver
